### ISSUE TITLE
Wrong parameters

### ISSUE THREAD

**Issue by hasselrot** [hemphen/homeassistant-clevertouch#7]
Since yesterday my integration is no longer working. Home assistant is giving this log.

```
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clevertouch/coordinator.py", line 79, in _async_update_data
    self.user = await self.api_session.get_user()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/clevertouch/objects.py", line 58, in get_user
    await user.refresh()
  File "/config/deps/lib/python3.11/site-packages/clevertouch/objects.py", line 121, in refresh
    data = await self._api_session.read_user_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/clevertouch/api.py", line 148, in read_user_data
    result = await self._read(endpoint, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/clevertouch/api.py", line 125, in _read
    raise ApiCallError(result.status, f"Read failed with {result.status}")
clevertouch.api.ApiCallError: Read failed with ERR_PARAM(3): Wrong parameters
2023-10-28 05:11:59.467 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-10-28 05:11:59.467 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2023-10-28 05:12:16.129 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-10-28 05:12:38.304 ERROR (MainThread) [custom_components.clevertouch.coordinator] Unexpected error fetching clevertouch-purmo-lars@hasselrot.net data: Read failed with ERR_PARAM(3): Wrong parameters
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clevertouch/coordinator.py", line 79, in _async_update_data
    self.user = await self.api_session.get_user()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/clevertouch/objects.py", line 58, in get_user
    await user.refresh()
  File "/config/deps/lib/python3.11/site-packages/clevertouch/objects.py", line 121, in refresh
    data = await self._api_session.read_user_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/clevertouch/api.py", line 148, in read_user_data
    result = await self._read(endpoint, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/clevertouch/api.py", line 125, in _read
    raise ApiCallError(result.status, f"Read failed with {result.status}")
clevertouch.api.ApiCallError: Read failed with ERR_PARAM(3): Wrong parameters
```

Can the API have been changed on e3 side?

**Comment by hemphen** [comment]
It's possible. Still works on my side though. Both reading and writing.

I restarted HomeAssistant to make sure it wasn't an initialization issue only.

I believe I am on an old version of HomeAssistant but that is likely irrelevant given the error message.

I did not attempt to remove the service and add it again.

Maybe you should at least try the restart.

(I of course assume that your installation works in the CleverTouch app.)

**Comment by hasselrot** [comment]
If it works for you, it is unlikely they introduced a breaking change on
their side. And the app works.

But I am on a rather new version of HA. Maybe the latest:
2023.11.0b1

**Comment by hemphen** [comment]
Fortunately Höstlov (school holiday) is coming up. I'll have time to upgrade and look into it.

There is another non-critical issue anyway that seems to have been introduced with newer versions HomeAssistant (#6).

**Comment by hasselrot** [comment]
Thats great!
Let me know if I can help and when to test!

**Comment by hemphen** [comment]
Upgraded to latest stable (container) version 20231005.0 without issues. Integration still works, perhaps "unfortunately" since it makes debugging much harder.

So, two simpler tests remains:

1) For you to reconfigure your account - it could possibly be your session token that has expired. It has some absurd lifetime - two years or so - meaning that I never got around to implement a refresh for it. I am not sure exactly how the reconfiguration affects your customizations though. I guess they will go unaffected given that you're not changing any names or device ids etc. but I can't promise anything. I would recommend backing up your config.

2) For me to install the beta - but it seems like a long shot.

If none of those works I need to implement better logging and you perhaps increase verbosity on your side.

**Comment by hasselrot** [comment]
Alright, it seems more and more likely that it is something on my side.

I can absolutely try to reconfigure the account. But how do I get the
integration to prompt for username/password again?
Is the token stored in some file that I could replace? I can easily get it
from the browser.

**Comment by hasselrot** [comment]
I got it!

The HA Gui was a bit buggy, but re-adding the integration from the
integration settings page eventually worked.

Thanks for the help!

**Comment by hemphen** [comment]
Great! I'll keep this issue open if someone else run into the same problem.

I also added a new issue #8 with the (supposedly) proper fix, which is supporting the reauthentication config flow.

**Comment by hemphen** [comment]
Authorization flow has changed and eauthorization should work now.
